# Generated by Django 5.2.7 on 2025-10-29 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0001_initial"),
        ("users", "0002_alter_user_role_memberprofile_trainerprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("personal", "Personal"),
                            ("group", "Group"),
                            ("class", "Class"),
                        ],
                        max_length=16,
                    ),
                ),
                ("scheduled_date", models.DateTimeField()),
                ("duration_minutes", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_sessions",
                        to="users.memberprofile",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_sessions",
                        to="users.trainerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_date"],
                "indexes": [
                    models.Index(
                        fields=["trainer", "scheduled_date"],
                        name="training_tr_trainer_3b5cd3_idx",
                    ),
                    models.Index(
                        fields=["member", "scheduled_date"],
                        name="training_tr_member__b7e99a_idx",
                    ),
                ],
            },
        ),
    ]
